version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "Build"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "composer"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
